CREATE DATABASE /*!32312 IF NOT EXISTS*/ `test` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

CREATE TABLE `test`.`test`  (
                                `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
                                `machine_id` char(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客户端唯一标识',
                                `host_name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
                                `name` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '别名',
                                `department_id` int NULL DEFAULT NULL,
                                `remark` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '备注',
                                `os` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '操作系统',
                                `os_type` tinyint(1) NULL DEFAULT 1 COMMENT '系统类型; 1:UOS  2:麒麟  3:Windows  4:CentOS  5:Ubuntu',
                                `status` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态，0：正常，1：停用',
                                `created_at` datetime(0) NOT NULL COMMENT '创建时间',
                                `update_admin_id` smallint UNSIGNED NOT NULL DEFAULT 0 COMMENT '修改此PC的管理员ID ',
                                `updated_at` datetime(0) NOT NULL COMMENT '编辑时间',
                                `need_upgrade` tinyint UNSIGNED NOT NULL DEFAULT 0,
                                `upgrade_at` datetime(0) NULL DEFAULT NULL COMMENT '系统更新时间',
                                `product_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `client_need_upgrade` tinyint(1) NULL DEFAULT NULL,
                                `minor_version` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `client_version` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `deleted_at` timestamp(0) NULL DEFAULT NULL,
                                `platform` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `arch` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `version` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
                                `online` tinyint(1) NULL DEFAULT NULL,
                                `last_login_time` timestamp(0) NULL DEFAULT NULL,
                                `last_logout_time` timestamp(0) NULL DEFAULT NULL,
                                `active_state` int NULL DEFAULT NULL COMMENT '系统激活状态，0未授权，1已授权，2已过期，3试用期已授',
                                `developer_mode` int NULL DEFAULT NULL COMMENT '开发者模式',
                                `ip` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'ip地址',
                                `mac` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'mac地址',
                                `sn` char(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '机器序列号,md5加密前的machine_id',
                                `user_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '加域人的账号',
                                `join_ip` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '入域时的ip',
                                `last_login_user_id` int NULL DEFAULT 0 COMMENT '最后使用人的id',
                                `last_login_full_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '最后使用人的全名',
                                PRIMARY KEY (`id`) USING BTREE,
                                UNIQUE INDEX `uuid`(`machine_id`) USING BTREE,
                                INDEX `sn`(`sn`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 130012 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = 'PC表' ROW_FORMAT = Dynamic;