version: '3'
services:
  mysql-slave-lb:
    image: nginx:latest
    container_name: mysql-2-slave-lb
    ports:
      - 23307:3307
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mysql
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
  mysql-master:
    image: mysql:5.7.35
    container_name: mysql-2-master
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MASTER_SYNC_USER: "sync_admin" #设置脚本中定义的用于同步的账号
      MASTER_SYNC_PASSWORD: "123456" #设置脚本中定义的用于同步的密码
      ADMIN_USER: "root" #当前容器用于拥有创建账号功能的数据库账号
      ADMIN_PASSWORD: "123456"
      ALLOW_HOST: "%.%.%.%" #允许同步账号的host地址
      TZ: "Asia/Shanghai" #解决时区问题
    ports:
      - 23306:3306
    networks:
      mysql:
        ipv4_address: "10.40.10.10" #固定ip，因为从库在连接master的时候，需要设置host
    volumes:
      - ./master:/docker-entrypoint-initdb.d #挂载master脚本
      - ./master/data:/var/lib/mysql
      - ./master/conf.d/mysql.conf:/etc/mysql/my.cnf
    command:
      -  "--server-id=20"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
      -  "--log-bin=mysql-bin"
      -  "--sync_binlog=1"
      -  "--skip-ssl"
  mysql-slave1:
    image: mysql:5.7.35
    container_name: mysql-2-slave1
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      SLAVE_SYNC_USER: "sync_admin" #用于同步的账号，由master创建
      SLAVE_SYNC_PASSWORD: "123456"
      ADMIN_USER: "root"
      ADMIN_PASSWORD: "123456"
      MASTER_HOST: "10.40.10.10" #master地址，开启主从同步需要连接master
      ALLOW_HOST: "%.%.%.%" #允许同步账号的host地址
      TZ: "Asia/Shanghai" #设置时区
    networks:
      mysql:
        ipv4_address: "10.40.10.20" #固定ip
    volumes:
      - ./slave1:/docker-entrypoint-initdb.d #挂载slave脚本
      - ./slave1/data:/var/lib/mysql
      - ./slave1/conf.d/mysql.conf:/etc/mysql/my.cnf
    command:
      -  "--server-id=21"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
      -  "--skip-ssl"
  mysql-slave2:
    image: mysql:5.7.35
    container_name: mysql-2-slave2
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      SLAVE_SYNC_USER: "sync_admin"
      SLAVE_SYNC_PASSWORD: "123456"
      ADMIN_USER: "root"
      ADMIN_PASSWORD: "123456"
      MASTER_HOST: "10.40.10.10"
      ALLOW_HOST: "%.%.%.%" #允许同步账号的host地址
      TZ: "Asia/Shanghai"
    networks:
      mysql:
        ipv4_address: "10.40.10.30" #固定ip
    volumes:
      - ./slave2:/docker-entrypoint-initdb.d #挂载slave脚本
      - ./slave2/data:/var/lib/mysql
      - ./slave2/conf.d/mysql.conf:/etc/mysql/my.cnf
    command: #这里需要修改server-id，保证每个mysql容器的server-id都不一样
      -  "--server-id=22"
      -  "--character-set-server=utf8mb4"
      -  "--collation-server=utf8mb4_unicode_ci"
      -  "--skip-ssl"
networks:
  mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.40.0.0/16"